#file: noinspection SpellCheckingInspection
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: lms
      POSTGRES_PASSWORD: lms
    ports:
      - '5432:5432'
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U lms']
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: lms
      RABBITMQ_DEFAULT_PASS: lms
    ports:
      - '5672:5672'
      - '15672:15672'
    tmpfs:
      - /var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'check_running']
      interval: 10s
      timeout: 10s
      retries: 5

  loki:
    image: grafana/loki:3.2.1
    ports:
      - '3100:3100'
    volumes:
      - ./docker/loki/local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:3100/ready']
      interval: 10s
      timeout: 5s
      retries: 5

  promtail:
    image: grafana/promtail:3.2.1
    volumes:
      - ./docker/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      loki:
        condition: service_healthy

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - '3030:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      loki:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      promtail:
        condition: service_started
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: lms
      DB_PASSWORD: lms
      DB_DATABASE: lms
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: lms
      RABBITMQ_PASSWORD: lms

  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: lms
      DB_PASSWORD: lms
      DB_DATABASE: lms
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: lms
      RABBITMQ_PASSWORD: lms

  course-service:
    build:
      context: .
      dockerfile: apps/course-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: lms
      DB_PASSWORD: lms
      DB_DATABASE: lms
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: lms
      RABBITMQ_PASSWORD: lms
  assignment-service:
    build:
      context: .
      dockerfile: apps/assignment-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: lms
      DB_PASSWORD: lms
      DB_DATABASE: lms
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: lms
      RABBITMQ_PASSWORD: lms

  course-enrollment-service:
    build:
      context: .
      dockerfile: apps/course-enrollment-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: lms
      DB_PASSWORD: lms
      DB_DATABASE: lms
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: lms
      RABBITMQ_PASSWORD: lms

  course-scheduling-service:
    build:
      context: .
      dockerfile: apps/course-scheduling-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: lms
      DB_PASSWORD: lms
      DB_DATABASE: lms
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: lms
      RABBITMQ_PASSWORD: lms

  file-service:
    build:
      context: .
      dockerfile: apps/file-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: lms
      DB_PASSWORD: lms
      DB_DATABASE: lms
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: lms
      RABBITMQ_PASSWORD: lms
