database:
  host: postgres
  port: 5432
  username: lms
  password: lms
  database: lms

rabbitmq:
  host: rabbitmq
  port: 5672
  username: lms
  password: lms
  eventExchange: lms-events
  eventQueue: lms-event-queue

health:
  port: 9000
  timeoutMs: 3000

logger:
  level: debug
  prettyPrint: true


storage:
  provider: local
  storagePath: /tmp/storage
